### GENERAL SETTINGS ###

# Site settings
title: TARVERN
author: Jon Gao
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://yourdomain.com"
header:
  color: "#000000"
  image: /assets/img/header-background.jpg
navbar:
  enabled: false


# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/
  arts:
    output: true
    permalink: /arts/:title/
  codes:
    output: true
    permalink: /codes/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: Twitter
    icon: /assets/svg/twitter-sign.svg
    url: https://twitter.com/jongaodev
  - title: Tumblr
    icon: /assets/svg/tumblr-logo.svg
    url: https://rosa89n20.tumblr.com
  - title: Github
    icon: /assets/svg/github-sign.svg
    url: https://github.com/rosa89n20
  - title: GameJolt
    icon: /assets/svg/gamejolt-sign.svg
    url: http://gamejolt.com/@rosa89n20
  - title: Itch.io
    icon: /assets/svg/itchio-sign.svg
    url: https://rosa89n20.itch.io/
  - title: DeviantArt
    icon: /assets/svg/deviantart-sign.svg
    url: http://rosa89n20.deviantart.com/
  - title: LinkedIn
    icon: /assets/svg/linkedin-sign.svg
    url: https://www.linkedin.com/in/rosa89n20/
  - title: Steam
    icon: /assets/svg/steam-sign.svg
    url: http://steamcommunity.com/id/rosa89n20
  - title: ArtStation
    icon: /assets/svg/artstation-sign.svg
    url: https://www.artstation.com/artist/rosa89n20

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about:
  avatar: /assets/img/about/avatar.jpg
  name: Jon Gao
  description: "Hell World!"
  experience:
    - job: Programer
      name: CSoft Taiwan
      time: Jul 2016 - Mar 2017
    - job: Programer
      name: Shinning Precision
      time: Jun 2014 - Jul 2016
    - job: Research and Teaching Assistant
      name: National Taiwan University and Lunghwa University
      time: Jan 2012 - Feb 2014
    - job: Game Jams, Personal Game Project, Freelance
      name: Battleham
      time: In spare time
  skills:
    - <strong>Solution Thinking</strong>, <strong>Design Mindset</strong>, <strong>Hobby Maker</strong>, <strong>Team Player</strong>, <strong>Self-Taught</strong>, <strong>Version Control</strong>, Team Managing
    - Mainly Unity, Visual Studio, GameMaker Studio, Spine, Flash, Photoshop, Arduino
    - Interactive design experience, Wii Remote, Kinect, VR(Oculus/Vive/Mobile), AR, LeapMotion, MYO. I'll make my own device with Arduino depend on usage case.
    - Front-end developing, HTML, CSS, Bootstrap, JavaScript, jQuery, Liquid. Integrate with WordPress and Jekyll
    - C#, JavaScript, ActionScript, GML, C++ on Arduino Project
  interests:
    - Hack and Slash, Couch-Multiplayer, Atmosphere, Blood, Lively game environment
    - Medieval Fantasy, Serious Sci-fi, Story Geek, Retro, Vaporwave
    - Love challenge, Solving problem, Experiment, Make random story

portfolio:
  img_width: 300
  img_height: 300
  grid_space: 10

defaults:
  -
    scope:
      path: "_projects"
    values:
      client: "Personal Project"
      alt: ""
      author: Jon Gao
      categories: ["project"]
      website: ""
  -
    scope:
      path: "_codes"
    values:
      website: ""
      thumbnail:
        - ""
  -
    scope:
      path: "_arts"
    values:
      website: ""
