# Site settings
title: Jon Gao
author: Jon Gao
description: "Game Developer, 2D Artist, Program Ranger. I love making video game, art and helping people, dreaming to become tavern master one day."
analytics: UA-46567973-4 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://rosa89n20.github.io"

# Component toggle
header:
  color: "#000000"
  image: /assets/img/header-background.jpg
navbar:
  enabled: false
content_guard: false
hoverEx: false

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#ce681e" #"#F70031"
  primary_rgb: "206,104,30" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#434343" #"#33004D"
  secondary_rgb: "67,67,67"
  link: "#fd9b14"
  link_hover: "#ce681e"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"
  contentBackground: "#313131"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/
  arts:
    output: true
    permalink: /arts/:title/
  codes:
    output: true
    permalink: /codes/:title/

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: EMail
    icon: /assets/svg/email-logo.svg
    url: mailto:rosa89n20@gmail.com
  - title: Twitter
    icon: /assets/svg/twitter-logo.svg
    url: https://twitter.com/jongaogame
  - title: Tumblr
    icon: /assets/svg/tumblr-logo.svg
    url: https://rosa89n20.tumblr.com
  - title: Github
    icon: /assets/svg/github-logo.svg
    url: https://github.com/rosa89n20
  - title: GameJolt
    icon: /assets/svg/gamejolt-logo.svg
    url: http://gamejolt.com/@rosa89n20
  - title: Itch.io
    icon: /assets/svg/itchio-logo.svg
    url: https://rosa89n20.itch.io/
  - title: DeviantArt
    icon: /assets/svg/deviantart-logo.svg
    url: http://rosa89n20.deviantart.com/
  - title: LinkedIn
    icon: /assets/svg/linkedin-logo.svg
    url: https://www.linkedin.com/in/rosa89n20/
  - title: Steam
    icon: /assets/svg/steam-logo.svg
    url: http://steamcommunity.com/id/rosa89n20
  - title: ArtStation
    icon: /assets/svg/artstation-logo.svg
    url: https://www.artstation.com/artist/rosa89n20

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about:
  avatar: /assets/img/about/avatar.jpg
  name: Jon Gao
  description: "Hello! I'm Jon, chinese name 高炯矗, aka Rosa or rosa89n20 on social media.<br>
   Just call me Jon if you getting confused already :D<br>
   Game developer, Illustrator and Hobby Maker in Taipei, Taiwan.<br>
   Graduated from Design school, Self-taught program since college.<br>
   I love play Game Jam with friends, Share dev log on social media, Watch Youtuber play my game and suffering!<br>
   I've big passion for programing as well as design, I like programing is because it constantly something new to learn and solve, I'm fast learner when it comes to tech and software.<br>
   I always love learn new technology, Solution thinking help me get through a lots of challenge, Design mindset help me crafted better.<br>
   All these make me not fear the unknown but embrace it.<br>
   That's why I have so many project from different area, and I respect all of them, they're the witness of my growing, and it'll never stop.<br>
   I also managing a group BATTLEHAM which is creative bunch help each other, freelance together.<br>
   I believe freelancing is attitude, to create mobility, helping people, keep yourself sharp all the time.<br>
   <br>
   When I'm not working I like adventure in alley, Pathfinding wothout Google Map. Reading, Drawing and experiment new code.<br>
   <br>
   Contact me via: rosa89n20@gmail.com"
  experience:
    - job: Technological Game Designer
      name: Playerium
      time: Jul 2017 - Feb 2018
    - job: Programer
      name: CSoft Taiwan
      time: Jul 2016 - Mar 2017
    - job: Programer
      name: Shinning Precision
      time: Jun 2014 - Jul 2016
    - job: Research and Teaching Assistant
      name: National Taiwan University and Lunghwa University
      time: Jan 2012 - Feb 2014
    - job: Game Jams, Personal Game Project, Freelance
      name: Battleham
      time: In spare time
  skills:
    - <strong>Solution Thinking</strong>, <strong>Design Mindset</strong>, <strong>Hobby Maker</strong>, <strong>Team Player</strong>, <strong>Self-Taught</strong>, <strong>Version Control</strong>, Team Managing
    - Mainly Unity, Visual Studio, GameMaker Studio, Spine, Flash, Photoshop, Arduino
    - Interactive design experience, Wii Remote, Kinect, VR(Oculus/Vive/Mobile), AR, LeapMotion, MYO. I'll make my own device with Arduino depend on usage case.
    - Front-end developing, HTML, CSS, Bootstrap, JavaScript, jQuery, Liquid. Integrate with WordPress and Jekyll
    - C#, JavaScript, ActionScript, GML, C++ on Arduino Project
  interests:
    - Hack and Slash, Couch-Multiplayer, Atmosphere, Blood, Lively game environment
    - Medieval Fantasy, Serious Sci-fi, Story Geek, Retro, Vaporwave
    - Love challenge, Solving problem, Experiment, Make random story
  carousel:
    - img: /assets/img/about/carousel/image-1.jpg
      alt: "Try to integration Scrum to our team"
    - img: /assets/img/about/carousel/image-2.jpg
      alt: "Share thought in school"
    - img: /assets/img/about/carousel/image-3.jpg
      alt: "Play board game with friends"

portfolio:
  img_width: 300
  img_height: 300
  grid_space: 10

# Default value for post across all
defaults:
  -
    scope:
      path: "_projects"
    values:
      client: "Personal Project"
      alt: ""
      author: Jon Gao
      categories: ["project"]
      website: ""
      genre: ""
      platform: ""
      priority: 0
  -
    scope:
      path: "_codes"
    values:
      website: ""
      thumbnail:
        - ""
  -
    scope:
      path: "_arts"
    values:
      website: ""
